<a href="https://colab.research.google.com/github/Rahulchunduruu/Machine-Learning/blob/main/Nextword_predction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models,callbacks
from tensorflow.keras.models import Sequential
from sklearn.metrics import classification_report,confusion_matrix


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM,Dense,Dropout,Bidirectional,Dropout
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.datasets import reuters

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
with open("/content/2024_state_of_the_union.txt",'r',encoding='utf-8') as f:
  data=f.read()

In [4]:
data

'March 07, 2024\nRemarks of President Joe Biden — State of the Union Address As Prepared for Delivery\nHome\nBriefing Room\nSpeeches and Remarks\nThe United States Capitol\n\n###\n\nGood evening. \n\nMr. Speaker. Madam Vice President. Members of Congress. My Fellow Americans. \n\nIn January 1941, President Franklin Roosevelt came to this chamber to speak to the nation. \n\nHe said, “I address you at a moment unprecedented in the history of the Union.” \n\nHitler was on the march. War was raging in Europe. \n\nPresident Roosevelt’s purpose was to wake up the Congress and alert the American people that this was no ordinary moment.   \n\nFreedom and democracy were under assault in the world. \n\nTonight I come to the same chamber to address the nation. \n\nNow it is we who face an unprecedented moment in the history of the Union. \n\nAnd yes, my purpose tonight is to both wake up this Congress, and alert the American people that this is no ordinary moment either. \n\nNot since President L

In [5]:
mytokenizer =  Tokenizer()
mytokenizer.fit_on_texts([data])
total_words = len(mytokenizer.word_index) + 1

In [6]:

mytokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'in': 6,
 'i': 7,
 'for': 8,
 'that': 9,
 'we': 10,
 'is': 11,
 'it': 12,
 'my': 13,
 'our': 14,
 'more': 15,
 'america': 16,
 'on': 17,
 'are': 18,
 'you': 19,
 'american': 20,
 'not': 21,
 'this': 22,
 'will': 23,
 'but': 24,
 'with': 25,
 'all': 26,
 'at': 27,
 'have': 28,
 'now': 29,
 'people': 30,
 'so': 31,
 'president': 32,
 'as': 33,
 'no': 34,
 'by': 35,
 'americans': 36,
 'down': 37,
 'future': 38,
 'was': 39,
 'they': 40,
 'can': 41,
 'want': 42,
 'from': 43,
 'home': 44,
 'up': 45,
 'it’s': 46,
 'than': 47,
 'their': 48,
 'has': 49,
 'here': 50,
 'be': 51,
 'i’ve': 52,
 'tonight': 53,
 'who': 54,
 'when': 55,
 'because': 56,
 'i’m': 57,
 'history': 58,
 'or': 59,
 'pay': 60,
 'year': 61,
 'do': 62,
 'make': 63,
 'tax': 64,
 'world': 65,
 'an': 66,
 'been': 67,
 'years': 68,
 'get': 69,
 'that’s': 70,
 '000': 71,
 'us': 72,
 'fair': 73,
 'families': 74,
 'act': 75,
 'care': 76,
 'predecessor': 77,
 'me': 78,
 'like': 79,
 '

In [7]:
#the length of words which we have in that text file
total_words=len(mytokenizer.word_index)+1
total_words

1624

In [8]:
my_input_sequneces=[]
for lines in data.split("\n"):
  token_list=mytokenizer.texts_to_sequences([lines])[0]
  #print(token_list)
  for i in range(1, len(token_list)):
    my_n_gram_sequence = token_list[:i+1]
    #print(my_n_gram_sequence)
    my_input_sequneces.append(my_n_gram_sequence)

In [9]:
print(my_input_sequneces)

[[270, 744], [270, 744, 482], [483, 4], [483, 4, 32], [483, 4, 32, 745], [483, 4, 32, 745, 746], [483, 4, 32, 745, 746, 484], [483, 4, 32, 745, 746, 484, 151], [483, 4, 32, 745, 746, 484, 151, 4], [483, 4, 32, 745, 746, 484, 151, 4, 1], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747, 8], [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747, 8, 748], [749, 485], [750, 2], [750, 2, 483], [1, 182], [1, 182, 132], [1, 182, 132, 486], [223, 751], [487, 752], [487, 752, 753], [487, 752, 753, 224], [487, 752, 753, 224, 32], [487, 752, 753, 224, 32, 488], [487, 752, 753, 224, 32, 488, 4], [487, 752, 753, 224, 32, 488, 4, 111], [487, 752, 753, 224, 32, 488, 4, 111, 13], [487, 752, 753, 224, 32, 488, 4, 111, 13, 489], [487, 752, 753, 224, 32, 488, 4, 111, 13, 489, 36], [6, 271]

In [10]:
max_sequence_len = max([len(seq) for seq in my_input_sequneces])
input_sequences = np.array(pad_sequences(my_input_sequneces,maxlen= max_sequence_len,padding = 'pre'))

In [11]:
input_sequences[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 270, 744], dtype=int32)

In [12]:
X = input_sequences[:,:-1]
y = input_sequences[:,-1]

In [13]:
y[0]

np.int32(744)

In [14]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 270], dtype=int32)

In [15]:
max_features=10000


In [16]:
def create_model():
  model=Sequential()
  model.add(Embedding(input_dim=max_features,output_dim=100,input_length=max_sequence_len-1))
  model.add(LSTM(units=128,return_sequences=True))
  model.add(Dropout(0.2))
  model.add(LSTM(64))
  model.add(Dropout(0.2))
  model.add(Dense(units=total_words,activation='softmax'))

  return model

In [17]:
lst_model=create_model()
lst_model.build(input_shape=(None, X.shape[1])) # Explicitly build the model
lst_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
from tensorflow.keras.utils import to_categorical
y_categorical = to_categorical(y, num_classes=total_words)

In [19]:
print(len(X),len(y_categorical))
print(len(X),len(y))

6069 6069
6069 6069


In [20]:
print(X[1])
print(y_categorical[1])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 270 744]
[0. 0. 0. ... 0. 0. 0.]


In [21]:
print(X[1])
print(y[1])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 270 744]
482


In [22]:
lst_model_history=lst_model.fit(X, y_categorical,epochs=100)



Epoch 1/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.0347 - loss: 6.9048
Epoch 2/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0465 - loss: 6.3077
Epoch 3/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.0483 - loss: 6.1919
Epoch 4/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0491 - loss: 6.1425
Epoch 5/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0512 - loss: 6.0911
Epoch 6/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0591 - loss: 5.9899
Epoch 7/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0609 - loss: 5.9639
Epoch 8/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0643 - loss: 5.8688
Epoch 9/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.0667 - loss: 5.7751
Epoch 10/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.0746 - loss: 5.6491
Epoch 11/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0784 - loss: 5.5926
Epoch 12/100
190/190 ━━━━━━━━━

In [23]:
lst_model.save('lst_model.keras')#save model